# The main makefile.
#
# This makefile contains commands that run after dependency generation.
# Commands that run before dependency generation are in 'Makefile'.

include variables.mk
include depend_hs.mk

.PHONY : default build install

default :
	echo "No target specified"

# Create executable and scripts; then run Python's setup script 
build : $(PYON_TARGET) $(PYON_GENERATED_SCRIPTS) src/pyon/data_dir.py
	python setup.py build

# Install Python library and files, pyon executable, and scripts
install : build
	python setup.py install --prefix=$(prefix) --exec-prefix=$(exec_prefix)
	install -d $(bindir)
	install $(PYON_TARGET) $(bindir)/pyon
	cd build/scripts; for sc in *; do install $${sc} $(bindir)/$${sc}; done

# Generate a Python file containing install path information
src/pyon/data_dir.py :
	echo "DATA_DIR=\"$(prefix)/share/pyon\" # Autogenerated" > src/pyon/data_dir.py

###############################################################################
# Compilation

# Compile a Haskell source file, found either in the source directory or in the
# build directory.
define COMPILE_HS_SOURCE
ifeq ($(shell test -f $(SRCDIR)/$(1) && echo yes),yes)
$(BUILDDIR)/$(1:.hs=.o) : $(SRCDIR)/$(1)
else
ifeq ($(shell test -f $(BUILDDIR)/$(1) && echo yes),yes)
$(BUILDDIR)/$(1:.hs=.o) : $(BUILDDIR)/$(1)
else
$(BUILDDIR)/$(1:.hs=.o) :
	echo "Cannot find file $(1)"
	exit 1
endif
endif
	mkdir -p $(BUILDDIR)/$(dir $(1))
	$(HC) -c $$< -odir $(BUILDDIR) -hidir $(BUILDDIR) -i$(BUILDDIR) $(HS_C_OPTS)
	touch $(BUILDDIR)/$(patsubst %.hs,%.hi,$(1))

endef

# Compile a C source file, found either in the source directory or in the
# build directory.
define COMPILE_C_SOURCE
ifeq ($(shell test -f $(SRCDIR)/$(1) && echo yes),yes)
$(BUILDDIR)/$(1:.c=.o) : $(SRCDIR)/$(1)
else
ifeq ($(shell test -f $(BUILDDIR)/$(1) && echo yes),yes)
$(BUILDDIR)/$(1:.c=.o) : $(BUILDDIR)/$(1)
else
$(BUILDDIR)/$(1:.c=.o) :
	echo "Cannot find file $(1)"
	exit 1
endif
endif
	mkdir -p $(BUILDDIR)/$(dir $(1))
	$(CC) -c $$< -o $$@ $(C_C_OPTS)

endef

# Compile all Haskell files
$(foreach hssrc, $(PYON_HS_SRCS) $(PYON_HS_GENERATED_SRCS),$(eval $(call COMPILE_HS_SOURCE,$(hssrc))))

# Compile all C files
$(foreach csrc, $(PYON_C_SRCS) $(PYON_C_GENERATED_SRCS),$(eval $(call COMPILE_C_SOURCE,$(csrc))))

# Link all object files
$(PYON_TARGET) : bin $(PYON_OBJECT_FILES)
	$(HC) $(PYON_OBJECT_FILES) -o $@ $(L_OPTS)

###############################################################################
# Generic rules

# To build a script, insert a line telling the shell how to execute the script
build/scripts/% : src/scripts/%
	mkdir -p build/scripts
	echo "#! $(bindir)/pyon" > $@
	cat $< >> $@

%.hi : %.o ;
%_stub.c : %.o ;
%_stub.h : %.o ;