
# Platform-specific settings
include config.mk

## Convert parameters into command line option strings

PACKAGE_FLAGS=$(foreach pkg, $(PACKAGES), -package $(pkg))
LIB_FLAGS=$(foreach lib, $(LIBS), -l$(lib))
INCLUDEDIR_FLAGS=-Isrc/program -I$(BUILDDIR) $(foreach dir, $(INCLUDEDIRS), -I$(dir))
LIBDIR_FLAGS=$(foreach dir, $(LIBDIRS), -L$(dir))

HS_HSC2HS_OPTS=$(HSC2HSFLAGS) $(INCLUDEDIR_FLAGS)
HS_C_OPTS=$(HCFLAGS) \
	-XMultiParamTypeClasses $(INCLUDEDIR_FLAGS) $(PACKAGE_FLAGS)
C_C_OPTS=$(CCFLAGS) $(INCLUDEDIR_FLAGS)
L_OPTS=$(LFLAGS) $(PACKAGE_FLAGS) $(LIDIR_FLAGS) $(LIB_FLAGS)

## File lists

PYON_C_SRCS=Main_c.c \
	PythonInterface/Python_c.c \
	PythonInterface/HsObject_c.c \
	Pyon/Exports/Gluon_c.c \
	Pyon/Exports/SystemF_c.c
PYON_C_GENERATED_SRCS=Parser/Driver_stub.c \
	Pyon/Exports/Gluon_stub.c \
	Pyon/Exports/SystemF_stub.c
PYON_HS_SRCS=Main.hs \
	Parser/Driver.hs \
	Parser/Parser.hs \
	Parser/Output.hs \
	Parser/ParserSyntax.hs \
	Pyon/Exports/Delayed.hs \
	Pyon/Exports/Gluon.hs \
	Pyon/Exports/SystemF.hs \
	Pyon/Globals.hs \
	Pyon/SystemF/Syntax.hs \
	Pyon/SystemF/Builtins.hs \
	Pyon/SystemF/Print.hs \
	Pyon/Core/Syntax.hs \
	Pyon/Core/Rename.hs \
	Pyon/Core/Typecheck.hs

PYON_HS_GENERATED_SRCS=Paths_pyon.hs \
	PythonInterface/Python.hs \
	PythonInterface/HsObject.hs

PYON_HS_OBJECTS=$(patsubst %.hs, %.o, $(PYON_HS_SRCS) $(PYON_HS_GENERATED_SRCS))
PYON_C_OBJECTS=$(patsubst %.c, %.o, $(PYON_C_SRCS) $(PYON_C_GENERATED_SRCS))
PYON_OBJECTS=$(PYON_HS_OBJECTS) $(PYON_C_OBJECTS)

PYON_SCRIPTS=pyon_testsuite pyon_compile
PYON_GENERATED_SCRIPTS=$(foreach sc, $(PYON_SCRIPTS), build/scripts/$(sc))

PYON_TARGET=build/pyon

# Object files with full path
PYON_OBJECT_FILES=$(foreach obj, $(PYON_OBJECTS), $(BUILDDIR)/$(obj))

###############################################################################
# Targets

.PHONY : all install clean veryclean build_bin build_python build_scripts install_bin install_python install_scripts

all : build_bin build_python build_scripts

install : install_bin install_python install_scripts $(PYON_TARGET)

clean :
	rm -f src/pyon/data_dir.py
	if [ -d build ]; then rm -rf build; fi

veryclean : clean
	find src -name "*~" -exec rm {} ';'
	rm -f config.log
	rm -f config.status
	rm -f config.mk
	rm -f configure
	rm -rf autom4te.cache
	if [ -d bin ]; then rm -f bin/*; rmdir bin; fi

bin :
	mkdir bin

build :
	mkdir build

build_bin : $(PYON_TARGET)

build_python : src/pyon/data_dir.py
	python setup.py build

build_scripts : $(PYON_GENERATED_SCRIPTS)

install_bin : build_bin
	install -d $(bindir)
	install $(PYON_TARGET) $(bindir)/pyon

install_python : build_python
	python setup.py install --prefix=$(prefix) --exec-prefix=$(exec_prefix)

install_scripts : build_scripts
	install -d $(bindir)
	cd build/scripts; for sc in *; do install $${sc} $(bindir)/$${sc}; done

src/pyon/data_dir.py :
	echo "DATA_DIR=\"$(prefix)/share/pyon\" # Autogenerated" > src/pyon/data_dir.py

###############################################################################
# Program 'pyon'

# Dependences
$(BUILDDIR)/Main_c.o : $(BUILDDIR)/Parser/Driver_stub.h
$(BUILDDIR)/Main_c.o : $(SRCDIR)/PythonInterface/HsObject.h
$(BUILDDIR)/PythonInterface/HsObject.o : $(SRCDIR)/PythonInterface/HsObject.h
$(BUILDDIR)/PythonInterface/HsObject.o : $(BUILDDIR)/PythonInterface/Python.hi
$(BUILDDIR)/Main.o : $(BUILDDIR)/Parser/Driver_stub.h
$(BUILDDIR)/Main.o : $(BUILDDIR)/PythonInterface/Python.hi
$(BUILDDIR)/Parser/Driver_stub.c \
 $(BUILDDIR)/Parser/Driver_stub.h \
 $(BUILDDIR)/Parser/Driver.o : $(BUILDDIR)/PythonInterface/Python.hi
$(BUILDDIR)/Parser/Driver_stub.c \
 $(BUILDDIR)/Parser/Driver_stub.h \
 $(BUILDDIR)/Parser/Driver.o : $(BUILDDIR)/Parser/Parser.hi
$(BUILDDIR)/Parser/Driver_stub.c \
 $(BUILDDIR)/Parser/Driver_stub.h \
 $(BUILDDIR)/Parser/Driver.o : $(BUILDDIR)/Parser/Output.hi
$(BUILDDIR)/Parser/Output.o : $(BUILDDIR)/PythonInterface/Python.hi
$(BUILDDIR)/Parser/Output.o : $(BUILDDIR)/Parser/ParserSyntax.hi
$(BUILDDIR)/Parser/Parser.o : $(BUILDDIR)/Parser/ParserSyntax.hi
$(BUILDDIR)/Pyon/Globals.o : $(BUILDDIR)/Pyon/SystemF/Builtins.hi
$(BUILDDIR)/Pyon/Globals.o : $(BUILDDIR)/Pyon/SystemF/Syntax.hi
$(BUILDDIR)/Pyon/Exports/Gluon_stub.c \
 $(BUILDDIR)/Pyon/Exports/Gluon_stub.h \
 $(BUILDDIR)/Pyon/Exports/Gluon.o \
 : $(BUILDDIR)/PythonInterface/HsObject.o
$(BUILDDIR)/Pyon/Exports/Gluon_stub.c \
 $(BUILDDIR)/Pyon/Exports/Gluon_stub.h \
 $(BUILDDIR)/Pyon/Exports/Gluon.o \
 : $(BUILDDIR)/Pyon/Globals.o
$(BUILDDIR)/Pyon/Exports/Gluon_c.o : $(BUILDDIR)/Pyon/Exports/Gluon_stub.h
$(BUILDDIR)/Pyon/Exports/SystemF_c.o : $(BUILDDIR)/Pyon/Exports/SystemF_stub.h
$(BUILDDIR)/Pyon/Exports/SystemF.o : $(BUILDDIR)/Pyon/SystemF/Syntax.hi
$(BUILDDIR)/Pyon/Exports/SystemF.o : $(BUILDDIR)/Pyon/SystemF/Print.hi
$(BUILDDIR)/Pyon/SystemF/Builtins.o : $(BUILDDIR)/Paths_pyon.hi
$(BUILDDIR)/Pyon/Core/Rename.o : $(BUILDDIR)/Pyon/Core/Syntax.hi
$(BUILDDIR)/Pyon/Core/Typecheck.o : $(BUILDDIR)/Pyon/Core/Syntax.hi
$(BUILDDIR)/Pyon/Core/Typecheck.o : $(BUILDDIR)/Pyon/Core/Rename.hi

# After invoking the compiler,
# touch interface files to ensure that their timestamps are updated
define PYON_COMPILE_HS_SOURCE
$(BUILDDIR)/$(1:.hs=.o) : $(BUILDDIR)/$(1)
	mkdir -p $(BUILDDIR)/$(dir $(1))
	$(HC) -c $$< -o $$@ -i$(BUILDDIR) $(HS_C_OPTS)
	touch $(BUILDDIR)/$(patsubst %.hs,%.hi,$(1))

endef

define PYON_COMPILE_C_SOURCE
$(BUILDDIR)/$(1:.c=.o) : $(SRCDIR)/$(1)
	mkdir -p $(BUILDDIR)/$(dir $(1))
	$(CC) -c $$< -o $$@ $(C_C_OPTS)

endef

$(BUILDDIR)/PythonInterface/Python.hs : $(SRCDIR)/PythonInterface/Python.hsc
	mkdir -p $(BUILDDIR)/PythonInterface
	$(HSC2HS) $(HS_HSC2HS_OPTS) $< -o $@

$(BUILDDIR)/PythonInterface/HsObject.hs : $(SRCDIR)/PythonInterface/HsObject.hsc
	mkdir -p $(BUILDDIR)/PythonInterface
	$(HSC2HS) $(HS_HSC2HS_OPTS) $< -o $@

$(eval $(call PYON_COMPILE_HS_SOURCE,Main.hs))
$(eval $(call PYON_COMPILE_HS_SOURCE,PythonInterface/Python.hs))
$(eval $(call PYON_COMPILE_HS_SOURCE,PythonInterface/HsObject.hs))
$(eval $(call PYON_COMPILE_HS_SOURCE,Parser/Parser.hs))
$(eval $(call PYON_COMPILE_HS_SOURCE,Parser/Output.hs))
$(eval $(call PYON_COMPILE_HS_SOURCE,Parser/ParserSyntax.hs))
$(eval $(call PYON_COMPILE_HS_SOURCE,Pyon/Globals.hs))
$(eval $(call PYON_COMPILE_HS_SOURCE,Pyon/SystemF/Syntax.hs))
$(eval $(call PYON_COMPILE_HS_SOURCE,Pyon/SystemF/Builtins.hs))
$(eval $(call PYON_COMPILE_HS_SOURCE,Pyon/SystemF/Print.hs))
$(eval $(call PYON_COMPILE_HS_SOURCE,Pyon/Exports/Delayed.hs))
$(eval $(call PYON_COMPILE_HS_SOURCE,Pyon/Core/Syntax.hs))
$(eval $(call PYON_COMPILE_HS_SOURCE,Pyon/Core/Rename.hs))
$(eval $(call PYON_COMPILE_HS_SOURCE,Pyon/Core/Typecheck.hs))

# 'Gluon.hs' has multiple targets, so it needs a distinct rule
# Touch output files to ensure their timestamps are updated
$(BUILDDIR)/Pyon/Exports/Gluon_stub.c \
 $(BUILDDIR)/Pyon/Exports/Gluon_stub.h \
 $(BUILDDIR)/Pyon/Exports/Gluon.o : $(BUILDDIR)/Pyon/Exports/Gluon.hs
	mkdir -p $(BUILDDIR)/Pyon/Exports
	$(HC) -c $< -o $(BUILDDIR)/Pyon/Exports/Gluon.o -i$(BUILDDIR) \
	 $(HS_C_OPTS)
	touch $(BUILDDIR)/Pyon/Exports/Gluon.hi
	touch $(BUILDDIR)/Pyon/Exports/Gluon_stub.c
	touch $(BUILDDIR)/Pyon/Exports/Gluon_stub.h

# 'SystemF.hs' has multiple targets, so it needs a distinct rule
# Touch output files to ensure their timestamps are updated
$(BUILDDIR)/Pyon/Exports/SystemF_stub.c \
 $(BUILDDIR)/Pyon/Exports/SystemF_stub.h \
 $(BUILDDIR)/Pyon/Exports/SystemF.o : $(BUILDDIR)/Pyon/Exports/SystemF.hs
	mkdir -p $(BUILDDIR)/Pyon/Exports
	$(HC) -c $< -o $(BUILDDIR)/Pyon/Exports/SystemF.o -i$(BUILDDIR) \
	 $(HS_C_OPTS)
	touch $(BUILDDIR)/Pyon/Exports/SystemF.hi
	touch $(BUILDDIR)/Pyon/Exports/SystemF_stub.c
	touch $(BUILDDIR)/Pyon/Exports/SystemF_stub.h

# 'Driver.hs' has multiple targets, so it needs a distinct rule
# Touch output files to ensure their timestamps are updated
$(BUILDDIR)/Parser/Driver_stub.c \
 $(BUILDDIR)/Parser/Driver_stub.h \
 $(BUILDDIR)/Parser/Driver.o : $(BUILDDIR)/Parser/Driver.hs
	mkdir -p $(BUILDDIR)/Parser
	$(HC) -c $< -o $(BUILDDIR)/Parser/Driver.o -i$(BUILDDIR) \
	 $(HS_C_OPTS)
	touch $(BUILDDIR)/Parser/Driver.hi
	touch $(BUILDDIR)/Parser/Driver_stub.c
	touch $(BUILDDIR)/Parser/Driver_stub.h

# Generate a file with path information
$(BUILDDIR)/Paths_pyon.hs :
	echo "{- Auto-generated source file -} module Paths_pyon where { import System.FilePath; getDataFileName :: String -> IO String; getDataFileName n = return (\"$(prefix)/share/pyon\" </> n) }" > $@

$(BUILDDIR)/Paths_pyon.o : $(BUILDDIR)/Paths_pyon.hs
	$(HC) -c $< -o $@ $(HS_C_OPTS)

$(eval $(call PYON_COMPILE_C_SOURCE,Main_c.c))
$(eval $(call PYON_COMPILE_C_SOURCE,PythonInterface/Python_c.c))
$(eval $(call PYON_COMPILE_C_SOURCE,PythonInterface/HsObject_c.c))
$(eval $(call PYON_COMPILE_C_SOURCE,Pyon/Exports/Gluon_c.c))
$(eval $(call PYON_COMPILE_C_SOURCE,Pyon/Exports/SystemF_c.c))

$(BUILDDIR)/Parser/Driver_stub.o : $(BUILDDIR)/Parser/Driver_stub.c
	$(CC) -c $< -o $@ $(C_C_OPTS)

$(BUILDDIR)/Pyon/Exports/Gluon_stub.o : $(BUILDDIR)/Pyon/Exports/Gluon_stub.c
	$(CC) -c $< -o $@ $(C_C_OPTS)

$(BUILDDIR)/Pyon/Exports/SystemF_stub.o : $(BUILDDIR)/Pyon/Exports/SystemF_stub.c
	$(CC) -c $< -o $@ $(C_C_OPTS)

$(PYON_TARGET) : bin $(PYON_OBJECT_FILES)
	$(HC) $(PYON_OBJECT_FILES) -o $@ $(L_OPTS)

###############################################################################
# Generic rules

# To build a script, insert a line telling the shell how to execute the script
build/scripts/% : src/scripts/%
	mkdir -p build/scripts
	echo "#! $(bindir)/pyon" > $@
	cat $< >> $@

$(BUILDDIR)/%.hs : $(SRCDIR)/%.hs
	mkdir -p $(dir $@)
	cp $< $@

%.hi : %.o ;
