{-| Hard-coded file paths used when building Pyon.
-}

module SetupPaths where

import System.FilePath

import Distribution.Simple
import Distribution.Simple.BuildPaths
import Distribution.Simple.LocalBuildInfo
import Distribution.PackageDescription

-- | The directories where source files belonging to the \"pyon\" program are
pyonSearchPaths :: LocalBuildInfo -> Executable -> [FilePath]
pyonSearchPaths lbi exe = autogenModulesDir lbi : hsSourceDirs (buildInfo exe)

-- | Destination for object files belonging to the \"pyon\" program
pyonBuildDir :: LocalBuildInfo -> FilePath
pyonBuildDir lbi = buildDir lbi </> "pyon"

-- | The directories where source files for the ComputeLayout program are
layoutSearchPaths :: LocalBuildInfo -> Executable -> [FilePath]
layoutSearchPaths lbi exe = autogenModulesDir lbi : "src/rts" : hsSourceDirs (buildInfo exe)

-- | Destination for object files belonging to the \"ComputeLayout\" program
layoutBuildDir :: LocalBuildInfo -> FilePath
layoutBuildDir lbi = buildDir lbi </> "rts"

-- | Directories containing source files belonging to the RTS
rtsSearchPaths :: LocalBuildInfo -> [FilePath]
rtsSearchPaths lbi = rtsBuildDir lbi : ["src/rts"]

-- | Destination for object files belonging to the RTS
rtsBuildDir :: LocalBuildInfo -> FilePath
rtsBuildDir lbi = buildDir lbi </> "rts"

-- | Destination for data files that will be installed
dataBuildDir :: LocalBuildInfo -> FilePath
dataBuildDir lbi = buildDir lbi </> "data"

-- | Directory containing regression tests
testSourceDir = "test"

-- | Path to autogenerated makefile
cabalMakeFile :: FilePath
cabalMakeFile = "cabal.mk"

-- | C Source files used in RTS
rtsCSourceFiles = ["apply_data.c", "memory.c", "debug.c"]

-- | Pyon-asm files used in RTS
rtsPyAsmFiles = ["apply_new.pyasm",
                 "memory_py.pyasm", "prim.pyasm", "structures.pyasm",
		 "list.pyasm", "stream.pyasm"]

-- | Data files that are not programmatically generated
prebuiltDataFiles = ["include/pyon.h", "include/pyon_list.h",
                     "symbols/coretypes", "symbols/SFBuiltin.glu"]
