{-| Hard-coded file paths used when building Pyon.
-}

module SetupPaths where

import System.FilePath

import Distribution.Simple
import Distribution.Simple.BuildPaths
import Distribution.Simple.LocalBuildInfo
import Distribution.PackageDescription

-- | The directories where source files belonging to the \"pyon\" program are
pyonSearchPaths :: LocalBuildInfo -> Executable -> [FilePath]
pyonSearchPaths lbi exe = autogenModulesDir lbi : hsSourceDirs (buildInfo exe)

-- | Destination for object files belonging to the \"pyon\" program
pyonBuildDir :: LocalBuildInfo -> FilePath
pyonBuildDir lbi = buildDir lbi </> "pyon"

-- | Directories containing source files belonging to the RTS
rtsSearchPaths :: LocalBuildInfo -> [FilePath]
rtsSearchPaths lbi = rtsBuildDir lbi : ["src/rts"]

-- | Destination for object files belonging to the RTS
rtsBuildDir :: LocalBuildInfo -> FilePath
rtsBuildDir lbi = buildDir lbi </> "rts"

-- | Destination for data files that will be installed
dataBuildDir :: LocalBuildInfo -> FilePath
dataBuildDir lbi = buildDir lbi </> "data"

-- | Path to autogenerated makefile
cabalMakeFile :: FilePath
cabalMakeFile = "cabal.mk"

-- | C Source files used in RTS
rtsCSourceFiles = ["struct.c", "memory.c", "apply.c"]

-- | Pyon-asm files used in RTS
rtsPyAsmFiles = ["memory_py.pyasm", "stream.pyasm"]

-- | Data files that are not programmatically generated
prebuiltDataFiles = ["include/pyon.h", "symbols/SFBuiltin.glu"]
