# This is a makefile, to be included by other makefiles.
# Variables are assigned here.

# Platform-specific settings generated by autoconf
include config.mk

# Source files and variables generated by cabal
include cabal.mk

## Convert parameters into command line option strings

PACKAGE_FLAGS=$(foreach pkg, $(PACKAGES), -package $(pkg))
TH_PACKAGE_FLAGS=$(foreach pkg, $(TH_PACKAGES), -package $(pkg))
LIB_FLAGS=$(foreach lib, $(LIBS), -l$(lib))

PYON_HS_INCLUDEDIR_FLAGS=\
  -isrc/program -i$(BUILDDIR)/pyon $(foreach dir, $(INCLUDEDIRS), -I$(dir))

C_INCLUDEDIR_FLAGS=\
  -Isrc/program -I$(BUILDDIR) $(foreach dir, $(INCLUDEDIRS), -I$(dir))

LIBDIR_FLAGS=$(foreach dir, $(LIBDIRS), -L$(dir))

HS_HSC2HS_OPTS=$(HSC2HSFLAGS) $(C_INCLUDEDIR_FLAGS)
HS_C_OPTS=$(HCFLAGS) -outputdir $(BUILDDIR)/pyon \
	-XMultiParamTypeClasses $(PYON_HS_INCLUDEDIR_FLAGS) $(TH_PACKAGE_FLAGS)
HS_TH_C_OPTS=$(HCFLAGS) -outputdir $(BUILDDIR)/pyon \
	-XMultiParamTypeClasses $(PYON_HS_INCLUDEDIR_FLAGS) $(TH_PACKAGE_FLAGS)
C_C_OPTS=$(CCFLAGS) $(C_INCLUDEDIR_FLAGS)

# Compile the RTS for dynamic linking.  RTS files will include the same header
# that compiled Pyon files will include; this file is found in the 'library'
# directory.
RTS_C_OPTS=-Ilibrary $(CCFLAGS) -dynamic

# Linker options used for the Pyon binary
L_OPTS=$(LFLAGS) $(PACKAGE_FLAGS) $(LIDIR_FLAGS) $(LIB_FLAGS)

## File lists

RTS_SRCS=pyon_rts.c

PYON_HS_OBJECTS=$(patsubst %.hs, %.o, $(PYON_HS_SRCS) $(PYON_TH_HS_SRCS) $(PYON_HS_GENERATED_SRCS))
PYON_C_OBJECTS=$(patsubst %.c, %.o, $(PYON_C_SRCS) $(PYON_C_GENERATED_SRCS))
PYON_OBJECTS=$(PYON_HS_OBJECTS) $(PYON_C_OBJECTS)

RTS_OBJECTS=$(patsubst %.c, %.o, $(RTS_SRCS))

PYON_SCRIPTS=pyon_testsuite pyon_compile
PYON_GENERATED_SCRIPTS=$(foreach sc, $(PYON_SCRIPTS), build/scripts/$(sc))

PYON_TARGET=$(BUILDDIR)/pyon/pyon
RTS_TARGET=$(BUILDDIR)/rts/pyonrts.so

# Object files with full path
RTS_OBJECT_FILES=$(foreach obj, $(RTS_OBJECTS), build/rts/$(obj))

